version: "3.8"
services:
  wisely-postgres:
    image: postgres:12
    ports:
      - "5459:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-databases.sql
    healthcheck:
      test: "pg_isready"
      interval: 10s
      timeout: 10s
      retries: 12
    networks:
      - wisely
networks:
  wisely:
